// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: timestamp_test.proto

package pb

import (
	_ "github.com/sunerpy/protoc-gen-jsonschema/mcp/jsonschema"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimestampTestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated timestamp (optional)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Required timestamp
	RequiredTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=required_timestamp,json=requiredTimestamp,proto3" json:"required_timestamp,omitempty"`
	// Array of timestamps
	EventTimestamps []*timestamppb.Timestamp `protobuf:"bytes,4,rep,name=event_timestamps,json=eventTimestamps,proto3" json:"event_timestamps,omitempty"`
	// Regular string field for comparison
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimestampTestMessage) Reset() {
	*x = TimestampTestMessage{}
	mi := &file_timestamp_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimestampTestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampTestMessage) ProtoMessage() {}

func (x *TimestampTestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_timestamp_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampTestMessage.ProtoReflect.Descriptor instead.
func (*TimestampTestMessage) Descriptor() ([]byte, []int) {
	return file_timestamp_test_proto_rawDescGZIP(), []int{0}
}

func (x *TimestampTestMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TimestampTestMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TimestampTestMessage) GetRequiredTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RequiredTimestamp
	}
	return nil
}

func (x *TimestampTestMessage) GetEventTimestamps() []*timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamps
	}
	return nil
}

func (x *TimestampTestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_timestamp_test_proto protoreflect.FileDescriptor

const file_timestamp_test_proto_rawDesc = "" +
	"\n" +
	"\x14timestamp_test.proto\x12\x04test\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fmcp/jsonschema/jsonschema.proto\"\xb7\x04\n" +
	"\x14TimestampTestMessage\x12i\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB.\x8a\xb5\x18\x12Creation timestamp\x92\xb5\x18\x142023-01-01T00:00:00ZR\tcreatedAt\x12T\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x19\x8a\xb5\x18\x15Last update timestampR\tupdatedAt\x12k\n" +
	"\x12required_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB \x8a\xb5\x18\x18Required timestamp field\xe0\xb5\x18\x01R\x11requiredTimestamp\x12d\n" +
	"\x10event_timestamps\x18\x04 \x03(\v2\x1a.google.protobuf.TimestampB\x1d\x8a\xb5\x18\x19Array of event timestampsR\x0feventTimestamps\x121\n" +
	"\x04name\x18\x05 \x01(\tB\x1d\x8a\xb5\x18\x19Name field for comparisonR\x04name:X\xaa\xbb\x18:Message for testing Timestamp field JSON Schema generation\xba\xbb\x18\x16Timestamp Test MessageB\fZ\n" +
	"test/pb;pbb\x06proto3"

var (
	file_timestamp_test_proto_rawDescOnce sync.Once
	file_timestamp_test_proto_rawDescData []byte
)

func file_timestamp_test_proto_rawDescGZIP() []byte {
	file_timestamp_test_proto_rawDescOnce.Do(func() {
		file_timestamp_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timestamp_test_proto_rawDesc), len(file_timestamp_test_proto_rawDesc)))
	})
	return file_timestamp_test_proto_rawDescData
}

var file_timestamp_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_timestamp_test_proto_goTypes = []any{
	(*TimestampTestMessage)(nil),  // 0: test.TimestampTestMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_timestamp_test_proto_depIdxs = []int32{
	1, // 0: test.TimestampTestMessage.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: test.TimestampTestMessage.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: test.TimestampTestMessage.required_timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: test.TimestampTestMessage.event_timestamps:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_timestamp_test_proto_init() }
func file_timestamp_test_proto_init() {
	if File_timestamp_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timestamp_test_proto_rawDesc), len(file_timestamp_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timestamp_test_proto_goTypes,
		DependencyIndexes: file_timestamp_test_proto_depIdxs,
		MessageInfos:      file_timestamp_test_proto_msgTypes,
	}.Build()
	File_timestamp_test_proto = out.File
	file_timestamp_test_proto_goTypes = nil
	file_timestamp_test_proto_depIdxs = nil
}
