// Code generated by protoc-gen-jsonschema. DO NOT EDIT.
// source: timestamp_test.proto

package pb

import (
	"encoding/json"

	"github.com/google/jsonschema-go/jsonschema"
)

// GetJSONSchema returns the JSON Schema for TimestampTestMessage
// Performance: ~0.29 ns/op, zero memory allocation
func (*TimestampTestMessage) GetJSONSchema() string {
	return timestampTestMessageSchemaJSON
}

// GetJSONSchemaBytes returns the JSON Schema as a byte array
// Useful for HTTP responses
// Performance: ~0.34 ns/op, zero memory allocation
func (*TimestampTestMessage) GetJSONSchemaBytes() []byte {
	return []byte(timestampTestMessageSchemaJSON)
}

// GetJSONSchemaRawMessage returns the JSON Schema as json.RawMessage
// Useful for JSON encoding without additional escaping
// Performance: ~0.34 ns/op, zero memory allocation
func (*TimestampTestMessage) GetJSONSchemaRawMessage() json.RawMessage {
	return json.RawMessage(timestampTestMessageSchemaJSON)
}

const timestampTestMessageSchemaJSON = `{"type":"object","title":"Timestamp Test Message","description":"Message for testing Timestamp field JSON Schema generation","properties":{"createdAt":{"description":"Creation timestamp","example":"2023-01-01T00:00:00Z","oneOf":[{"description":"RFC3339 timestamp string","format":"date-time","type":"string"},{"additionalProperties":false,"properties":{"nanos":{"description":"Nanoseconds within the second","maximum":999999999,"minimum":0,"type":"integer"},"seconds":{"description":"Seconds since Unix epoch","type":"integer"}},"required":["seconds"],"type":"object"}]},"updatedAt":{"description":"Last update timestamp","oneOf":[{"description":"RFC3339 timestamp string","format":"date-time","type":"string"},{"additionalProperties":false,"properties":{"nanos":{"description":"Nanoseconds within the second","maximum":999999999,"minimum":0,"type":"integer"},"seconds":{"description":"Seconds since Unix epoch","type":"integer"}},"required":["seconds"],"type":"object"}]},"requiredTimestamp":{"description":"Required timestamp field","oneOf":[{"description":"RFC3339 timestamp string","format":"date-time","type":"string"},{"additionalProperties":false,"properties":{"nanos":{"description":"Nanoseconds within the second","maximum":999999999,"minimum":0,"type":"integer"},"seconds":{"description":"Seconds since Unix epoch","type":"integer"}},"required":["seconds"],"type":"object"}]},"eventTimestamps":{"description":"Array of event timestamps","items":{"oneOf":[{"description":"RFC3339 timestamp string","format":"date-time","type":"string"},{"additionalProperties":false,"properties":{"nanos":{"description":"Nanoseconds within the second","maximum":999999999,"minimum":0,"type":"integer"},"seconds":{"description":"Seconds since Unix epoch","type":"integer"}},"required":["seconds"],"type":"object"}]},"type":"array"},"name":{"description":"Name field for comparison","type":"string"}},"required":["requiredTimestamp"]}`

// timestampTestMessageGoogleSchema is the compile-time Google JSON Schema for TimestampTestMessage
// This is a Google jsonschema.Schema struct literal, requiring zero runtime parsing
// Can be used directly with github.com/google/jsonschema-go for validation
// Performance: Direct struct access, zero initialization overhead, zero parsing cost
var timestampTestMessageGoogleSchema = &jsonschema.Schema{
	Type:        "object",
	Title:       "Timestamp Test Message",
	Description: "Message for testing Timestamp field JSON Schema generation",
	Properties: map[string]*jsonschema.Schema{
		"createdAt": &jsonschema.Schema{
			Description: "Creation timestamp",
			Examples:    []any{"2023-01-01T00:00:00Z"},
			OneOf: []*jsonschema.Schema{
				&jsonschema.Schema{
					Type:        "string",
					Description: "RFC3339 timestamp string",
					Format:      "date-time",
				},
				&jsonschema.Schema{
					Type:                 "object",
					AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
					Properties: map[string]*jsonschema.Schema{
						"nanos": &jsonschema.Schema{
							Type:        "integer",
							Description: "Nanoseconds within the second",
							Minimum:     &[]float64{0}[0],
							Maximum:     &[]float64{9.99999999e+08}[0],
						},
						"seconds": &jsonschema.Schema{
							Type:        "integer",
							Description: "Seconds since Unix epoch",
						},
					},
					Required: []string{"seconds"},
				},
			},
		},
		"eventTimestamps": &jsonschema.Schema{
			Type:        "array",
			Description: "Array of event timestamps",
			Items: &jsonschema.Schema{
				OneOf: []*jsonschema.Schema{
					&jsonschema.Schema{
						Type:        "string",
						Description: "RFC3339 timestamp string",
						Format:      "date-time",
					},
					&jsonschema.Schema{
						Type:                 "object",
						AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
						Properties: map[string]*jsonschema.Schema{
							"nanos": &jsonschema.Schema{
								Type:        "integer",
								Description: "Nanoseconds within the second",
								Minimum:     &[]float64{0}[0],
								Maximum:     &[]float64{9.99999999e+08}[0],
							},
							"seconds": &jsonschema.Schema{
								Type:        "integer",
								Description: "Seconds since Unix epoch",
							},
						},
						Required: []string{"seconds"},
					},
				},
			},
		},
		"name": &jsonschema.Schema{
			Type:        "string",
			Description: "Name field for comparison",
		},
		"requiredTimestamp": &jsonschema.Schema{
			Description: "Required timestamp field",
			OneOf: []*jsonschema.Schema{
				&jsonschema.Schema{
					Type:        "string",
					Description: "RFC3339 timestamp string",
					Format:      "date-time",
				},
				&jsonschema.Schema{
					Type:                 "object",
					AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
					Properties: map[string]*jsonschema.Schema{
						"nanos": &jsonschema.Schema{
							Type:        "integer",
							Description: "Nanoseconds within the second",
							Minimum:     &[]float64{0}[0],
							Maximum:     &[]float64{9.99999999e+08}[0],
						},
						"seconds": &jsonschema.Schema{
							Type:        "integer",
							Description: "Seconds since Unix epoch",
						},
					},
					Required: []string{"seconds"},
				},
			},
		},
		"updatedAt": &jsonschema.Schema{
			Description: "Last update timestamp",
			OneOf: []*jsonschema.Schema{
				&jsonschema.Schema{
					Type:        "string",
					Description: "RFC3339 timestamp string",
					Format:      "date-time",
				},
				&jsonschema.Schema{
					Type:                 "object",
					AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
					Properties: map[string]*jsonschema.Schema{
						"nanos": &jsonschema.Schema{
							Type:        "integer",
							Description: "Nanoseconds within the second",
							Minimum:     &[]float64{0}[0],
							Maximum:     &[]float64{9.99999999e+08}[0],
						},
						"seconds": &jsonschema.Schema{
							Type:        "integer",
							Description: "Seconds since Unix epoch",
						},
					},
					Required: []string{"seconds"},
				},
			},
		},
	},
	Required: []string{"requiredTimestamp"},
}

// GetGoogleSchema returns the compile-time Google JSON Schema struct for TimestampTestMessage
// Unlike GetJSONSchema() which returns a string that needs json.Unmarshal,
// this method returns a pre-built Google jsonschema.Schema struct with zero parsing overhead
// Can be used directly for validation with github.com/google/jsonschema-go
// Performance: Direct variable access, zero allocation, zero parsing
func (*TimestampTestMessage) GetGoogleSchema() *jsonschema.Schema {
	return timestampTestMessageGoogleSchema
}
