// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mcp/jsonschema/jsonschema.proto

package jsonschema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_mcp_jsonschema_jsonschema_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "mcp.jsonschema.description",
		Tag:           "bytes,50001,opt,name=description",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "mcp.jsonschema.example",
		Tag:           "bytes,50002,opt,name=example",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "mcp.jsonschema.format",
		Tag:           "bytes,50003,opt,name=format",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "mcp.jsonschema.default",
		Tag:           "bytes,50004,opt,name=default",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50005,
		Name:          "mcp.jsonschema.hidden",
		Tag:           "varint,50005,opt,name=hidden",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50006,
		Name:          "mcp.jsonschema.json_name",
		Tag:           "bytes,50006,opt,name=json_name",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50007,
		Name:          "mcp.jsonschema.min_length",
		Tag:           "varint,50007,opt,name=min_length",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50008,
		Name:          "mcp.jsonschema.max_length",
		Tag:           "varint,50008,opt,name=max_length",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*float64)(nil),
		Field:         50009,
		Name:          "mcp.jsonschema.minimum",
		Tag:           "fixed64,50009,opt,name=minimum",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*float64)(nil),
		Field:         50010,
		Name:          "mcp.jsonschema.maximum",
		Tag:           "fixed64,50010,opt,name=maximum",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50011,
		Name:          "mcp.jsonschema.pattern",
		Tag:           "bytes,50011,opt,name=pattern",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50012,
		Name:          "mcp.jsonschema.required",
		Tag:           "varint,50012,opt,name=required",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50101,
		Name:          "mcp.jsonschema.message_description",
		Tag:           "bytes,50101,opt,name=message_description",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50102,
		Name:          "mcp.jsonschema.generate_schema",
		Tag:           "varint,50102,opt,name=generate_schema",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50103,
		Name:          "mcp.jsonschema.title",
		Tag:           "bytes,50103,opt,name=title",
		Filename:      "mcp/jsonschema/jsonschema.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// 自定义描述（优先级高于注释）
	//
	// optional string description = 50001;
	E_Description = &file_mcp_jsonschema_jsonschema_proto_extTypes[0]
	// 示例值
	//
	// optional string example = 50002;
	E_Example = &file_mcp_jsonschema_jsonschema_proto_extTypes[1]
	// JSON Schema format (e.g., "email", "uri", "date-time")
	//
	// optional string format = 50003;
	E_Format = &file_mcp_jsonschema_jsonschema_proto_extTypes[2]
	// 默认值（JSON 格式字符串）
	//
	// optional string default = 50004;
	E_Default = &file_mcp_jsonschema_jsonschema_proto_extTypes[3]
	// 是否在 Schema 中隐藏此字段
	//
	// optional bool hidden = 50005;
	E_Hidden = &file_mcp_jsonschema_jsonschema_proto_extTypes[4]
	// 自定义 JSON 字段名（如果与 proto 字段名不同）
	//
	// optional string json_name = 50006;
	E_JsonName = &file_mcp_jsonschema_jsonschema_proto_extTypes[5]
	// 字符串最小长度
	//
	// optional int32 min_length = 50007;
	E_MinLength = &file_mcp_jsonschema_jsonschema_proto_extTypes[6]
	// 字符串最大长度
	//
	// optional int32 max_length = 50008;
	E_MaxLength = &file_mcp_jsonschema_jsonschema_proto_extTypes[7]
	// 数值最小值
	//
	// optional double minimum = 50009;
	E_Minimum = &file_mcp_jsonschema_jsonschema_proto_extTypes[8]
	// 数值最大值
	//
	// optional double maximum = 50010;
	E_Maximum = &file_mcp_jsonschema_jsonschema_proto_extTypes[9]
	// 正则表达式模式
	//
	// optional string pattern = 50011;
	E_Pattern = &file_mcp_jsonschema_jsonschema_proto_extTypes[10]
	// 是否必填
	//
	// optional bool required = 50012;
	E_Required = &file_mcp_jsonschema_jsonschema_proto_extTypes[11]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// 消息描述
	//
	// optional string message_description = 50101;
	E_MessageDescription = &file_mcp_jsonschema_jsonschema_proto_extTypes[12]
	// 是否生成 Schema（默认 true）
	//
	// optional bool generate_schema = 50102;
	E_GenerateSchema = &file_mcp_jsonschema_jsonschema_proto_extTypes[13]
	// Schema 标题
	//
	// optional string title = 50103;
	E_Title = &file_mcp_jsonschema_jsonschema_proto_extTypes[14]
)

var File_mcp_jsonschema_jsonschema_proto protoreflect.FileDescriptor

const file_mcp_jsonschema_jsonschema_proto_rawDesc = "" +
	"\n" +
	"\x1fmcp/jsonschema/jsonschema.proto\x12\x0emcp.jsonschema\x1a google/protobuf/descriptor.proto:D\n" +
	"\vdescription\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\vdescription\x88\x01\x01:<\n" +
	"\aexample\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\tR\aexample\x88\x01\x01::\n" +
	"\x06format\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\tR\x06format\x88\x01\x01:<\n" +
	"\adefault\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\tR\adefault\x88\x01\x01::\n" +
	"\x06hidden\x12\x1d.google.protobuf.FieldOptions\x18Ն\x03 \x01(\bR\x06hidden\x88\x01\x01:?\n" +
	"\tjson_name\x12\x1d.google.protobuf.FieldOptions\x18ֆ\x03 \x01(\tR\bjsonName\x88\x01\x01:A\n" +
	"\n" +
	"min_length\x12\x1d.google.protobuf.FieldOptions\x18׆\x03 \x01(\x05R\tminLength\x88\x01\x01:A\n" +
	"\n" +
	"max_length\x12\x1d.google.protobuf.FieldOptions\x18؆\x03 \x01(\x05R\tmaxLength\x88\x01\x01:<\n" +
	"\aminimum\x12\x1d.google.protobuf.FieldOptions\x18ن\x03 \x01(\x01R\aminimum\x88\x01\x01:<\n" +
	"\amaximum\x12\x1d.google.protobuf.FieldOptions\x18چ\x03 \x01(\x01R\amaximum\x88\x01\x01:<\n" +
	"\apattern\x12\x1d.google.protobuf.FieldOptions\x18ۆ\x03 \x01(\tR\apattern\x88\x01\x01:>\n" +
	"\brequired\x12\x1d.google.protobuf.FieldOptions\x18܆\x03 \x01(\bR\brequired\x88\x01\x01:U\n" +
	"\x13message_description\x12\x1f.google.protobuf.MessageOptions\x18\xb5\x87\x03 \x01(\tR\x12messageDescription\x88\x01\x01:M\n" +
	"\x0fgenerate_schema\x12\x1f.google.protobuf.MessageOptions\x18\xb6\x87\x03 \x01(\bR\x0egenerateSchema\x88\x01\x01::\n" +
	"\x05title\x12\x1f.google.protobuf.MessageOptions\x18\xb7\x87\x03 \x01(\tR\x05title\x88\x01\x01BDZBgithub.com/sunerpy/protoc-gen-jsonschema/mcp/jsonschema;jsonschemab\x06proto3"

var file_mcp_jsonschema_jsonschema_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),   // 0: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_mcp_jsonschema_jsonschema_proto_depIdxs = []int32{
	0,  // 0: mcp.jsonschema.description:extendee -> google.protobuf.FieldOptions
	0,  // 1: mcp.jsonschema.example:extendee -> google.protobuf.FieldOptions
	0,  // 2: mcp.jsonschema.format:extendee -> google.protobuf.FieldOptions
	0,  // 3: mcp.jsonschema.default:extendee -> google.protobuf.FieldOptions
	0,  // 4: mcp.jsonschema.hidden:extendee -> google.protobuf.FieldOptions
	0,  // 5: mcp.jsonschema.json_name:extendee -> google.protobuf.FieldOptions
	0,  // 6: mcp.jsonschema.min_length:extendee -> google.protobuf.FieldOptions
	0,  // 7: mcp.jsonschema.max_length:extendee -> google.protobuf.FieldOptions
	0,  // 8: mcp.jsonschema.minimum:extendee -> google.protobuf.FieldOptions
	0,  // 9: mcp.jsonschema.maximum:extendee -> google.protobuf.FieldOptions
	0,  // 10: mcp.jsonschema.pattern:extendee -> google.protobuf.FieldOptions
	0,  // 11: mcp.jsonschema.required:extendee -> google.protobuf.FieldOptions
	1,  // 12: mcp.jsonschema.message_description:extendee -> google.protobuf.MessageOptions
	1,  // 13: mcp.jsonschema.generate_schema:extendee -> google.protobuf.MessageOptions
	1,  // 14: mcp.jsonschema.title:extendee -> google.protobuf.MessageOptions
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	0,  // [0:15] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_jsonschema_jsonschema_proto_init() }
func file_mcp_jsonschema_jsonschema_proto_init() {
	if File_mcp_jsonschema_jsonschema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_jsonschema_jsonschema_proto_rawDesc), len(file_mcp_jsonschema_jsonschema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 15,
			NumServices:   0,
		},
		GoTypes:           file_mcp_jsonschema_jsonschema_proto_goTypes,
		DependencyIndexes: file_mcp_jsonschema_jsonschema_proto_depIdxs,
		ExtensionInfos:    file_mcp_jsonschema_jsonschema_proto_extTypes,
	}.Build()
	File_mcp_jsonschema_jsonschema_proto = out.File
	file_mcp_jsonschema_jsonschema_proto_goTypes = nil
	file_mcp_jsonschema_jsonschema_proto_depIdxs = nil
}
