// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	_ "github.com/sunerpy/protoc-gen-jsonschema/mcp/jsonschema"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User's email address
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// User's full name (3-50 characters)
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// User's age (must be 18-120)
	Age int32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// User's phone number (optional)
	Phone         string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\aexample\x1a\x1fmcp/jsonschema/jsonschema.proto\"\xfd\x02\n" +
	"\vUserRequest\x12O\n" +
	"\x05email\x18\x01 \x01(\tB9\x8a\xb5\x18\x14User's email address\x92\xb5\x18\x10user@example.com\x9a\xb5\x18\x05email\xe0\xb5\x18\x01R\x05email\x12@\n" +
	"\x04name\x18\x02 \x01(\tB,\x8a\xb5\x18\x10User's full name\x92\xb5\x18\bJohn Doe\xb8\xb5\x18\x03\xc0\xb5\x182\xe0\xb5\x18\x01R\x04name\x12?\n" +
	"\x03age\x18\x03 \x01(\x05B-\x8a\xb5\x18\x13User's age in yearsɵ\x18\x00\x00\x00\x00\x00\x002@ѵ\x18\x00\x00\x00\x00\x00\x00^@R\x03age\x12b\n" +
	"\x05phone\x18\x04 \x01(\tBL\x8a\xb5\x18#User's phone number in E.164 format\x92\xb5\x18\v+1234567890ڵ\x18\x12^\\+?[1-9]\\d{1,14}$R\x05phone:6\xaa\xbb\x18\"Request to create or update a user\xba\xbb\x18\fUser Request\"\xac\x01\n" +
	"\x0eProductRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\x8a\xb5\x18\fProduct name\xe0\xb5\x18\x01R\x04name\x122\n" +
	"\x05price\x18\x02 \x01(\x01B\x1c\x8a\xb5\x18\rProduct priceɵ\x18{\x14\xaeG\xe1z\x84?R\x05price:<\xaa\xbb\x18%Request to create or update a product\xba\xbb\x18\x0fProduct RequestB\x0fZ\rexample/pb;pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_proto_goTypes = []any{
	(*UserRequest)(nil),    // 0: example.UserRequest
	(*ProductRequest)(nil), // 1: example.ProductRequest
}
var file_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
