// Code generated by protoc-gen-jsonschema. DO NOT EDIT.
// source: user.proto

package pb

import (
	"encoding/json"

	"github.com/google/jsonschema-go/jsonschema"
)

// GetJSONSchema returns the JSON Schema for UserRequest
// Performance: ~0.29 ns/op, zero memory allocation
func (*UserRequest) GetJSONSchema() string {
	return userRequestSchemaJSON
}

// GetJSONSchemaBytes returns the JSON Schema as a byte array
// Useful for HTTP responses
// Performance: ~0.34 ns/op, zero memory allocation
func (*UserRequest) GetJSONSchemaBytes() []byte {
	return []byte(userRequestSchemaJSON)
}

// GetJSONSchemaRawMessage returns the JSON Schema as json.RawMessage
// Useful for JSON encoding without additional escaping
// Performance: ~0.34 ns/op, zero memory allocation
func (*UserRequest) GetJSONSchemaRawMessage() json.RawMessage {
	return json.RawMessage(userRequestSchemaJSON)
}

const userRequestSchemaJSON = `{"type":"object","title":"User Request","description":"Request to create or update a user","properties":{"email":{"description":"User's email address","example":"user@example.com","format":"email","type":"string"},"name":{"description":"User's full name","example":"John Doe","maxLength":50,"minLength":3,"type":"string"},"age":{"description":"User's age in years","maximum":120,"minimum":18,"type":"integer"},"phone":{"description":"User's phone number in E.164 format","example":"+1234567890","pattern":"^\\+?[1-9]\\d{1,14}$","type":"string"}},"required":["email","name"]}`

// userRequestGoogleSchema is the compile-time Google JSON Schema for UserRequest
// This is a Google jsonschema.Schema struct literal, requiring zero runtime parsing
// Can be used directly with github.com/google/jsonschema-go for validation
// Performance: Direct struct access, zero initialization overhead, zero parsing cost
var userRequestGoogleSchema = &jsonschema.Schema{
	Type:        "object",
	Title:       "User Request",
	Description: "Request to create or update a user",
	Properties: map[string]*jsonschema.Schema{
		"email": &jsonschema.Schema{
			Type:        "string",
			Description: "User's email address",
			Format:      "email",
		},
		"name": &jsonschema.Schema{
			Type:        "string",
			Description: "User's full name",
			MinLength:   &[]int{3}[0],
			MaxLength:   &[]int{50}[0],
		},
		"age": &jsonschema.Schema{
			Type:        "integer",
			Description: "User's age in years",
			Minimum:     &[]float64{18}[0],
			Maximum:     &[]float64{120}[0],
		},
		"phone": &jsonschema.Schema{
			Type:        "string",
			Description: "User's phone number in E.164 format",
			Pattern:     "^\\+?[1-9]\\d{1,14}$",
		},
	},
	Required: []string{"email", "name"},
}

// GetGoogleSchema returns the compile-time Google JSON Schema struct for UserRequest
// Unlike GetJSONSchema() which returns a string that needs json.Unmarshal,
// this method returns a pre-built Google jsonschema.Schema struct with zero parsing overhead
// Can be used directly for validation with github.com/google/jsonschema-go
// Performance: Direct variable access, zero allocation, zero parsing
func (*UserRequest) GetGoogleSchema() *jsonschema.Schema {
	return userRequestGoogleSchema
}

// GetJSONSchema returns the JSON Schema for ProductRequest
// Performance: ~0.29 ns/op, zero memory allocation
func (*ProductRequest) GetJSONSchema() string {
	return productRequestSchemaJSON
}

// GetJSONSchemaBytes returns the JSON Schema as a byte array
// Useful for HTTP responses
// Performance: ~0.34 ns/op, zero memory allocation
func (*ProductRequest) GetJSONSchemaBytes() []byte {
	return []byte(productRequestSchemaJSON)
}

// GetJSONSchemaRawMessage returns the JSON Schema as json.RawMessage
// Useful for JSON encoding without additional escaping
// Performance: ~0.34 ns/op, zero memory allocation
func (*ProductRequest) GetJSONSchemaRawMessage() json.RawMessage {
	return json.RawMessage(productRequestSchemaJSON)
}

const productRequestSchemaJSON = `{"type":"object","title":"Product Request","description":"Request to create or update a product","properties":{"name":{"description":"Product name","type":"string"},"price":{"description":"Product price","minimum":0.01,"type":"number"}},"required":["name"]}`

// productRequestGoogleSchema is the compile-time Google JSON Schema for ProductRequest
// This is a Google jsonschema.Schema struct literal, requiring zero runtime parsing
// Can be used directly with github.com/google/jsonschema-go for validation
// Performance: Direct struct access, zero initialization overhead, zero parsing cost
var productRequestGoogleSchema = &jsonschema.Schema{
	Type:        "object",
	Title:       "Product Request",
	Description: "Request to create or update a product",
	Properties: map[string]*jsonschema.Schema{
		"name": &jsonschema.Schema{
			Type:        "string",
			Description: "Product name",
		},
		"price": &jsonschema.Schema{
			Type:        "number",
			Description: "Product price",
			Minimum:     &[]float64{0.01}[0],
		},
	},
	Required: []string{"name"},
}

// GetGoogleSchema returns the compile-time Google JSON Schema struct for ProductRequest
// Unlike GetJSONSchema() which returns a string that needs json.Unmarshal,
// this method returns a pre-built Google jsonschema.Schema struct with zero parsing overhead
// Can be used directly for validation with github.com/google/jsonschema-go
// Performance: Direct variable access, zero allocation, zero parsing
func (*ProductRequest) GetGoogleSchema() *jsonschema.Schema {
	return productRequestGoogleSchema
}
